name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vim_version:
        - 'v8.2.3000'
        - 'v8.2.2000'
        - 'v8.2.1000'
        - 'v8.2.0000'
        - 'v8.1.0000'
        - 'v8.0.0000'
        - 'v7.4'

    steps:
    - name: Checkout code
      uses: actions/checkout@master

    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - name: Setup Bundle
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Setup Vim
      uses: thinca/action-setup-vim@v1
      with:
        vim_version: ${{ matrix.vim_version }}

    - name: Install Dependencies
      run: | 
        curl -f -L "https://raw.githubusercontent.com/vim-airline/vim-airline-themes/master/autoload/airline/themes/simple.vim" -o autoload/airline/themes/simple.vim
        curl -f -L "https://raw.githubusercontent.com/vim-airline/vim-airline-themes/master/autoload/airline/themes/molokai.vim" -o autoload/airline/themes/molokai.vim
        mkdir colors && curl -f -L 'https://raw.githubusercontent.com/tomasr/molokai/master/colors/molokai.vim' -o colors/molokai.vim

    - name: Run Test
      run: rake ci
